# Generated by Django 5.2.17 on 2026-10-02 09:53

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('benefit', 'Преимущество'), ('step', 'Шаг аренды'), ('condition', 'Условие аренды')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Legion Auto Rent', max_length=100)),
                ('phone', models.CharField(default='+7 (705) 727-77-77', max_length=40)),
                ('whatsapp', models.CharField(default='77057277777', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('hours', models.CharField(blank=True, max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to='site/', validators=[core.validators.validate_image])),
                ('favicon', models.ImageField(blank=True, upload_to='site/', validators=[core.validators.validate_image])),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', validators=[core.validators.validate_image])),
                ('hero_model', models.FileField(blank=True, help_text='Лицензированный GLB до 5 МБ. Draco assets поддерживаются.', upload_to='models/', validators=[core.validators.validate_glb])),
                ('hero_model_license', models.CharField(blank=True, help_text='Источник и подтверждение прав на модель', max_length=250)),
                ('hero_title', models.CharField(default='Прокат авто без водителя в Астане', max_length=200)),
                ('hero_text', models.TextField(default='Для деловых встреч, городских маршрутов и поездок за город. Выберите свой автомобиль — остальное возьмём на себя.')),
                ('instagram', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='Автомобиль под ваши планы.', max_length=250)),
                ('gtm_id', models.CharField(blank=True, max_length=30)),
                ('ga4_id', models.CharField(blank=True, max_length=30)),
                ('metrika_id', models.CharField(blank=True, max_length=30)),
                ('google_verification', models.CharField(blank=True, max_length=150)),
                ('yandex_verification', models.CharField(blank=True, max_length=150)),
                ('show_partner_section', models.BooleanField(default=True)),
                ('partner_title', models.CharField(default='Стать партнером Легионавто', max_length=200)),
                ('partner_description', models.TextField(default='Вы можете стать нашим партнером предоставив нам ваше авто на субаренду.')),
                ('partner_phone', models.CharField(blank=True, help_text='Если пусто, используется основной телефон', max_length=40)),
                ('partner_whatsapp', models.CharField(blank=True, help_text='Если пусто, используется основной WhatsApp', max_length=20)),
                ('partner_whatsapp_message', models.TextField(default='Здравствуйте! Хочу узнать подробнее о партнерстве с Легионавто и передаче автомобиля в субаренду.')),
                ('hero_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cars.car')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
