# Generated by Django 5.2.17 on 2026-10-02 20:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_seo_description',
            field=models.TextField(default='Аренда автомобилей без водителя в Казахстане. Автопарк, цены и контакты Legion Auto Rent.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_seo_title',
            field=models.CharField(default='Legion Auto Rent — прокат автомобилей', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_hero_3d',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_hero_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_model_path',
            field=models.CharField(default='/static/models/hero.glb', help_text='Локальный путь GLB; загрузка файла выше имеет приоритет.', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_names',
            field=models.JSONField(default=core.models.default_hero_names),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_placeholder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_poster_path',
            field=models.CharField(default='/static/img/hero-poster.webp', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_path',
            field=models.CharField(blank=True, help_text='Необязательный локальный WebM; показывается вместо 3D только по настройке.', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='robots_text',
            field=models.TextField(blank=True, help_text='Production robots; {sitemap_url} заменяется автоматически. Staging всегда закрыт.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.TextField(default='Здравствуйте! Интересует аренда автомобиля в Legion Auto Rent.'),
        ),
    ]
