# Generated by Django 5.2.17 on 2026-10-02 20:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_default_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_model',
            field=models.FileField(blank=True, help_text='Лицензированный GLB до 3 МБ. Draco и meshopt поддерживаются.', upload_to='models/', validators=[core.validators.validate_glb]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_model_path',
            field=models.CharField(default='/static/models/hero.glb', help_text='Локальный путь GLB; для сохранённого hero.glb браузер использует hero-compressed.glb. Загрузка файла выше имеет приоритет.', max_length=250),
        ),
    ]
