# Generated by Django 5.2.17 on 2026-10-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_hero_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_ending_path',
            field=models.CharField(blank=True, default='/static/hero/mercedes-ending-1f6aa0701c89.webp', max_length=250, verbose_name='Финальный кадр'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_poster_path',
            field=models.CharField(blank=True, default='/static/hero/mercedes-front-mobile-940302853d4f.webp', max_length=250, verbose_name='Постер для телефона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_hero_video',
            field=models.BooleanField(default=True, verbose_name='Анимация при прокрутке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_poster_path',
            field=models.CharField(default='/static/hero/mercedes-front-77ca8545d4d0.webp', max_length=250, verbose_name='Постер первого экрана'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Без водителя. Под ваши планы.', help_text='Текст в конце анимации. H1 берётся только из SEO города и здесь не меняется.', max_length=200, verbose_name='Финальная подпись'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_path',
            field=models.CharField(blank=True, default='/static/hero/mercedes-segment-01-43d4cc20ca42.mp4', help_text='Локальный MP4 /static/ или /media/. H.264, без звука, ключевой кадр каждые 8 кадров.', max_length=250, verbose_name='Видео первого экрана'),
        ),
    ]
