# Generated by Django 5.2.17 on 2026-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_hero_ending_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_price_caption',
            field=models.CharField(blank=True, help_text='Второй этап видео. Если пусто: от 20 000 ₸ / сутки.', max_length=150, verbose_name='Подпись о цене'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_steps_caption',
            field=models.CharField(blank=True, help_text='Третий этап видео. Если пусто: звонок, доставка по городу, договор за 10 минут.', max_length=250, verbose_name='Три шага — короткая строка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_ending_path',
            field=models.CharField(blank=True, default='/static/hero/hero-ending-87350d5b2b8d.webp', max_length=250, verbose_name='Финальный кадр'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_mobile_poster_path',
            field=models.CharField(blank=True, default='/static/hero/hero-static-27f030789025.webp', max_length=250, verbose_name='Постер для телефона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_poster_path',
            field=models.CharField(default='/static/hero/hero-poster-e9b496d7a585.webp', max_length=250, verbose_name='Постер первого экрана'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_path',
            field=models.CharField(blank=True, default='/static/hero/hero-scrub-4836d5f97269.mp4', help_text='Локальный MP4 /static/ или /media/. H.264, без звука, ключевой кадр каждые 8 кадров.', max_length=250, verbose_name='Видео первого экрана'),
        ),
    ]
