# Generated by Django 5.2.17 on 2026-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_hero_price_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_path',
            field=models.CharField(blank=True, default='/static/hero/hero-scrub-smooth60-c86f40f74879.mp4', help_text='Локальный MP4 /static/ или /media/. H.264, без звука, ключевой кадр каждые 8 кадров.', max_length=250, verbose_name='Видео первого экрана'),
        ),
    ]
