# Generated by Django 5.2.17 on 2026-10-05 09:28

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_showroom_smooth_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500, unique=True, verbose_name='Исходная подпись')),
                ('section', models.CharField(max_length=150, verbose_name='Раздел сайта')),
                ('ru', models.TextField(blank=True, help_text='Пусто — используется исходная подпись.', verbose_name='Русский')),
                ('kk', models.TextField(blank=True, help_text='Пусто — используется существующий перевод сайта.', verbose_name='Қазақша')),
                ('en', models.TextField(blank=True, help_text='Пусто — используется существующий перевод сайта.', verbose_name='English')),
            ],
            options={
                'verbose_name': 'Подпись интерфейса',
                'verbose_name_plural': 'Тексты и кнопки',
                'ordering': ['section', 'source'],
            },
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('fleet', 'Автопарк'), ('categories', 'Строка классов'), ('steps', 'Шаги аренды'), ('benefits', 'Преимущества'), ('seo', 'Описание города'), ('faq', 'Вопросы и ответы'), ('partner', 'Партнёрам'), ('contacts', 'Контакты')], max_length=30, unique=True, verbose_name='Блок')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел главной и городов',
                'verbose_name_plural': 'Порядок разделов',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_ending_image',
            field=models.ImageField(blank=True, upload_to='site/hero/', validators=[core.validators.validate_image], verbose_name='Загрузить финальный кадр'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_image',
            field=models.ImageField(blank=True, upload_to='site/hero/', validators=[core.validators.validate_image], verbose_name='Загрузить кадр для телефона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='MP4 H.264 без звука, до 20 МБ. Новая загрузка заменяет активный путь ниже; старый файл сохраняется.', upload_to='site/hero/', validators=[core.validators.validate_hero_video], verbose_name='Загрузить видео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_fps',
            field=models.PositiveSmallIntegerField(default=60, help_text='Для текущего ролика — 60. При замене укажите фактическую частоту кадров.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Частота кадров видео'),
        ),
    ]
