# Generated by Django 5.2.17 on 2026-10-05 09:34

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_interfacetext_sitesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('main', 'Шапка'), ('mobile', 'Мобильное меню')], max_length=20, verbose_name='Меню')),
                ('label', models.CharField(max_length=80, verbose_name='Подпись RU')),
                ('label_kk', models.CharField(blank=True, max_length=100, verbose_name='Подпись KZ')),
                ('label_en', models.CharField(blank=True, max_length=100, verbose_name='Подпись EN')),
                ('path', models.CharField(help_text='Существующий адрес, например /cars/. Языковой префикс добавляется автоматически.', max_length=250, validators=[seo.models.validate_local_path], verbose_name='Страница сайта')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ссылка меню',
                'verbose_name_plural': 'Навигация',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
