# Generated by Django 5.2.17 on 2026-10-05 09:40

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carbrand_options_alter_cardiscount_options_and_more'),
        ('core', '0009_seed_cms_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='kind',
            field=models.CharField(choices=[('benefit', 'Преимущество'), ('step', 'Шаг аренды'), ('condition', 'Условие аренды')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_seo_description',
            field=models.TextField(default='Аренда автомобилей без водителя в Казахстане. Автопарк, цены и контакты Legion Auto Rent.', verbose_name='Запасной Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_seo_title',
            field=models.CharField(default='Legion Auto Rent — прокат автомобилей', max_length=250, verbose_name='Запасной Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='site/', validators=[core.validators.validate_image], verbose_name='Иконка сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='Автомобиль под ваши планы.', max_length=250, verbose_name='Подпись в подвале'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ga4_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='GA4 — справочный ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_verification',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подтверждение Google'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gtm_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Контейнер Google Tag Manager'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cars.car', verbose_name='Автомобиль для резервного режима'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='site/', validators=[core.validators.validate_image], verbose_name='Загрузить первый кадр'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_text',
            field=models.TextField(default='Для деловых встреч, городских маршрутов и поездок за город. Выберите свой автомобиль — остальное возьмём на себя.', verbose_name='Описание первого экрана'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours',
            field=models.CharField(blank=True, max_length=120, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/', validators=[core.validators.validate_image], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на встроенную карту Яндекса'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='metrika_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Метрика — справочный ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='Legion Auto Rent', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Уведомления о заявках'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='partner_description',
            field=models.TextField(default='Вы можете стать нашим партнером предоставив нам ваше авто на субаренду.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='partner_phone',
            field=models.CharField(blank=True, help_text='Если пусто, используется основной телефон', max_length=40, verbose_name='Телефон партнёров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='partner_title',
            field=models.CharField(default='Стать партнером Легионавто', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='partner_whatsapp',
            field=models.CharField(blank=True, help_text='Если пусто, используется основной WhatsApp', max_length=20, verbose_name='WhatsApp партнёров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='partner_whatsapp_message',
            field=models.TextField(default='Здравствуйте! Хочу узнать подробнее о партнерстве с Легионавто и передаче автомобиля в субаренду.', verbose_name='Сообщение для партнёров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+7 (705) 727-77-77', max_length=40, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='robots_text',
            field=models.TextField(blank=True, help_text='Production robots; {sitemap_url} заменяется автоматически. Staging всегда закрыт.', verbose_name='Инструкции robots.txt'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_partner_section',
            field=models.BooleanField(default=True, verbose_name='Показывать блок партнёров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(default='77057277777', max_length=20, verbose_name='Номер WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.TextField(default='Здравствуйте! Интересует аренда автомобиля в Legion Auto Rent.', verbose_name='Сообщение в WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подтверждение Яндекса'),
        ),
    ]
