# Generated by Django 5.2.17 on 2026-10-05 11:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bugfix_interface_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_video_file',
            field=models.FileField(blank=True, help_text='Необязательный отдельный MP4 без звука. Пустое поле сохраняет текущую анимацию.', upload_to='site/hero/', validators=[core.validators.validate_hero_video], verbose_name='Анимация для телефона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_mobile_video_path',
            field=models.CharField(blank=True, help_text='Пусто: готовый цикл для утверждённого видео или основной загруженный ролик.', max_length=250, verbose_name='Путь анимации для телефона'),
        ),
    ]
