# Generated by Django 5.2.17 on 2026-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_uppercase_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_seo_description',
            field=models.TextField(default='Аренда автомобилей без водителя в Казахстане. Автопарк, цены и контакты LEGIONAUTORENT.', verbose_name='Запасной Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_seo_title',
            field=models.CharField(default='LEGIONAUTORENT — прокат автомобилей', max_length=250, verbose_name='Запасной Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='LEGIONAUTORENT', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='partner_title',
            field=models.CharField(default='Стать партнером LEGIONAUTORENT', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='partner_whatsapp_message',
            field=models.TextField(default='Здравствуйте! Хочу узнать подробнее о партнерстве с LEGIONAUTORENT и передаче автомобиля в субаренду.', verbose_name='Сообщение для партнёров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.TextField(default='Здравствуйте! Интересует аренда автомобиля в LEGIONAUTORENT.', verbose_name='Сообщение в WhatsApp'),
        ),
    ]
