# Generated by Django 5.2.17 on 2026-10-06 08:37

from django.db import migrations, models



def use_new_master(apps, schema_editor):
    Site = apps.get_model('core', 'SiteSettings')
    replacements = {
        'hero_video_path': ('/static/hero/hero-60fps.mp4', ('hero-scrub-', 'mercedes-segment-')),
        'hero_poster_path': ('/static/hero/hero-poster-60fps-desktop.webp', ('hero-poster-', 'mercedes-front-')),
        'hero_mobile_poster_path': ('/static/hero/hero-poster-60fps-mobile.webp', ('hero-static-', 'mercedes-front-mobile-')),
        'hero_ending_path': ('/static/hero/hero-ending-60fps.webp', ('hero-ending-', 'mercedes-ending-')),
        'hero_mobile_video_path': ('', ('hero-mobile-loop-',)),
    }
    for field, (replacement, prefixes) in replacements.items():
        for prefix in prefixes:
            Site.objects.filter(**{field+'__startswith': '/static/hero/'+prefix}).exclude(**{field: replacement}).update(**{field: replacement})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_uppercase_brand_defaults'),
    ]

    operations = [
        migrations.RunPython(use_new_master, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_ending_path',
            field=models.CharField(blank=True, default='/static/hero/hero-ending-60fps.webp', max_length=250, verbose_name='Финальный кадр'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_mobile_poster_path',
            field=models.CharField(blank=True, default='/static/hero/hero-poster-60fps-mobile.webp', max_length=250, verbose_name='Постер для телефона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_poster_path',
            field=models.CharField(default='/static/hero/hero-poster-60fps-desktop.webp', max_length=250, verbose_name='Постер первого экрана'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_path',
            field=models.CharField(blank=True, default='/static/hero/hero-60fps.mp4', help_text='Локальный MP4 /static/ или /media/. H.264, без звука, ключевой кадр каждые 8 кадров.', max_length=250, verbose_name='Видео первого экрана'),
        ),
    ]
