# Generated by Django 5.2.17 on 2026-10-02 09:53

import django.db.models.deletion
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='H1')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical override')),
                ('robots', models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40)),
                ('og_title', models.CharField(blank=True, max_length=250)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('path', models.CharField(max_length=250, unique=True, validators=[seo.models.validate_local_path])),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, verbose_name='Содержимое HTML')),
                ('active', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('legal_approved', models.BooleanField(default=False, help_text='Юридические страницы требуют утверждения владельцем.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cars.car')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='locations.city')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='pages.page')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
