# Generated by Django 5.2.17 on 2026-10-05 09:40

import django.db.models.deletion
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carbrand_options_alter_cardiscount_options_and_more'),
        ('locations', '0005_alter_city_active_alter_city_address_and_more'),
        ('pages', '0002_page_legacy_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='locations.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='pages.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='page',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступление'),
        ),
        migrations.AlterField(
            model_name='page',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные Open Graph/Twitter поля сохранены для точной миграции.', verbose_name='Сохранённые метаданные'),
        ),
        migrations.AlterField(
            model_name='page',
            name='legal_approved',
            field=models.BooleanField(default=False, help_text='Юридические страницы требуют утверждения владельцем.', verbose_name='Текст утверждён владельцем'),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_image',
            field=models.URLField(blank=True, verbose_name='Адрес картинки для соцсетей'),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(max_length=250, unique=True, validators=[seo.models.validate_local_path], verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='robots',
            field=models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40, verbose_name='Индексация'),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=False, verbose_name='Ссылка в подвале'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Код в адресе (slug)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
