server {
    listen 8080;
    server_name legionautorent.kz www.legionautorent.kz;
    location /.well-known/acme-challenge/ { root /var/www/acme; }
    location / { return 301 https://legionautorent.kz$request_uri; }
}
server {
    listen 8443 ssl;
    server_name www.legionautorent.kz;
    ssl_certificate /etc/letsencrypt/live/legionautorent.kz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/legionautorent.kz/privkey.pem;
    return 301 https://legionautorent.kz$request_uri;
}
server {
    listen 8443 ssl;
    server_name legionautorent.kz;
    ssl_certificate /etc/letsencrypt/live/legionautorent.kz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/legionautorent.kz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    include /etc/nginx/legion/shared.conf;
}
