# Generated by Django 5.2.17 on 2026-10-02 09:53

import core.validators
import django.core.validators
import django.db.models.deletion
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='H1')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical override')),
                ('robots', models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40)),
                ('og_title', models.CharField(blank=True, max_length=250)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Класс автомобиля',
                'verbose_name_plural': 'Классы автомобилей',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='H1')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical override')),
                ('robots', models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40)),
                ('og_title', models.CharField(blank=True, max_length=250)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('legacy_path', models.CharField(max_length=250, unique=True, validators=[seo.models.validate_local_path])),
                ('legacy_id', models.CharField(max_length=250, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена в сутки, ₸')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Автомат'), ('manual', 'Механика')], max_length=20)),
                ('drive', models.CharField(blank=True, choices=[('front', 'Передний'), ('rear', 'Задний'), ('all', 'Полный')], max_length=20)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('color', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('accepts_requests', models.BooleanField(default=True, help_text='Это не проверка свободных дат.', verbose_name='Принимать заявки')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cities', models.ManyToManyField(related_name='cars', to='locations.city')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carcategory')),
                ('features', models.ManyToManyField(blank=True, to='cars.carfeature')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CarDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='cars.car')),
            ],
            options={
                'ordering': ['min_days'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='cars/originals/', validators=[core.validators.validate_image])),
                ('image', models.ImageField(blank=True, upload_to='cars/webp/', validators=[core.validators.validate_image])),
                ('small', models.ImageField(blank=True, upload_to='cars/webp/', validators=[core.validators.validate_image])),
                ('legacy_url', models.URLField(blank=True, max_length=600)),
                ('alt', models.CharField(blank=True, max_length=250)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1200)),
                ('height', models.PositiveIntegerField(default=800)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['-is_main', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(blank=True, max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cars.car')),
            ],
            options={
                'ordering': ['min_days'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['active', 'base_price'], name='cars_car_active_d2600b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['featured', 'sort_order'], name='cars_car_feature_5d6f0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_url', ''), _negated=True), fields=('car', 'legacy_url'), name='unique_legacy_car_image'),
        ),
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('car',), name='one_main_image_per_car'),
        ),
    ]
