# Generated by Django 5.2.17 on 2026-10-02 10:24

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='legacy_path',
            field=models.CharField(blank=True, help_text='Пустое поле: автоматически /car/slug. Существующий путь не меняется.', max_length=250, unique=True, validators=[seo.models.validate_local_path]),
        ),
    ]
