# Generated by Django 5.2.17 on 2026-10-02 10:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_legacy_id_alter_car_legacy_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='card_height',
            field=models.PositiveIntegerField(default=619),
        ),
        migrations.AddField(
            model_name='carimage',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='cars/webp/', validators=[core.validators.validate_image]),
        ),
        migrations.AddField(
            model_name='carimage',
            name='card_small',
            field=models.ImageField(blank=True, upload_to='cars/webp/', validators=[core.validators.validate_image]),
        ),
        migrations.AddField(
            model_name='carimage',
            name='card_width',
            field=models.PositiveIntegerField(default=960),
        ),
    ]
