# Generated by Django 5.2.17 on 2026-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_deposit_car_doors_car_fuel_car_mileage_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные Open Graph/Twitter поля сохранены для точной миграции.'),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные Open Graph/Twitter поля сохранены для точной миграции.'),
        ),
    ]
