# Generated by Django 5.2.17 on 2026-10-05 09:40

import core.validators
import django.core.validators
import django.db.models.deletion
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_legacy_meta_carcategory_legacy_meta'),
        ('locations', '0005_alter_city_active_alter_city_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Марка', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='cardiscount',
            options={'ordering': ['min_days'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='carfeature',
            options={'verbose_name': 'Оснащение', 'verbose_name_plural': 'Оснащение'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['-is_main', 'sort_order', 'pk'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='carprice',
            options={'ordering': ['min_days'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='carspecification',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carbrand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carcategory', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cities',
            field=models.ManyToManyField(related_name='cars', to='locations.city', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='car',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Депозит, ₸'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Двери'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(blank=True, choices=[('front', 'Передний'), ('rear', 'Задний'), ('all', 'Полный')], max_length=20, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Выделить в каталоге'),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, to='cars.carfeature', verbose_name='Оснащение'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='car',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='ID исходного сайта'),
        ),
        migrations.AlterField(
            model_name='car',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные Open Graph/Twitter поля сохранены для точной миграции.', verbose_name='Сохранённые метаданные'),
        ),
        migrations.AlterField(
            model_name='car',
            name='legacy_path',
            field=models.CharField(blank=True, help_text='Пустое поле: автоматически /car/slug. Существующий путь не меняется.', max_length=250, unique=True, validators=[seo.models.validate_local_path], verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег в сутки, км'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='og_image',
            field=models.URLField(blank=True, verbose_name='Адрес картинки для соцсетей'),
        ),
        migrations.AlterField(
            model_name='car',
            name='og_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='robots',
            field=models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40, verbose_name='Индексация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Код в адресе (slug)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Автомат'), ('manual', 'Механика')], max_length=20, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код в адресе (slug)'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные Open Graph/Twitter поля сохранены для точной миграции.', verbose_name='Сохранённые метаданные'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='og_image',
            field=models.URLField(blank=True, verbose_name='Адрес картинки для соцсетей'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='og_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='robots',
            field=models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40, verbose_name='Индексация'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код в адресе (slug)'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='cardiscount',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='cardiscount',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='cardiscount',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='До дней'),
        ),
        migrations.AlterField(
            model_name='cardiscount',
            name='min_days',
            field=models.PositiveIntegerField(verbose_name='От дней'),
        ),
        migrations.AlterField(
            model_name='cardiscount',
            name='percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='alt',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание фото (alt)'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='legacy_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='Исходный адрес изображения'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='original',
            field=models.ImageField(upload_to='cars/originals/', validators=[core.validators.validate_image], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='daily_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='В сутки, ₸'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Депозит, ₸'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='До дней'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='mileage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег в сутки, км'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='min_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='От дней'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_specs', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='value',
            field=models.CharField(max_length=250, verbose_name='Значение'),
        ),
    ]
