const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const copy = (from, to) => { fs.mkdirSync(path.dirname(to), {recursive: true}); fs.copyFileSync(from,to); };
const n = path.join(root,'node_modules'); const v = path.join(root,'static','vendor');
for (const name of ['three.module.js','three.core.js']) copy(path.join(n,'three','build',name),path.join(v,'three',name));
for (const name of ['loaders/GLTFLoader.js','loaders/DRACOLoader.js','utils/BufferGeometryUtils.js']) copy(path.join(n,'three','examples','jsm',name),path.join(v,'three','addons',name));
for (const name of ['draco_wasm_wrapper.js','draco_decoder.wasm']) copy(path.join(n,'three','examples','jsm','libs','draco','gltf',name),path.join(v,'three','draco',name));
copy(path.join(n,'gsap','dist','gsap.min.js'),path.join(v,'gsap','gsap.min.js'));
copy(path.join(n,'three','LICENSE'),path.join(v,'three','LICENSE'));
fs.writeFileSync(path.join(v,'gsap','LICENSE_SOURCE.md'),'GSAP Standard License: https://gsap.com/community/standard-license/\nVersion: '+JSON.parse(fs.readFileSync(path.join(n,'gsap','package.json'))).version+'\n');
console.log('Three.js, Draco and GSAP assets vendored locally.');
