"""Write the new SSR interface. Legacy source remains in the Git checkpoint."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
files={
'templates/base.html':r'''{% load static i18n legion_tags %}<!doctype html>
<html lang="{{ current_language }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#1F1F1F">
<title>{{ seo.title }}</title><meta name="description" content="{{ seo.description }}"><meta name="robots" content="{{ seo.robots }}"><link rel="canonical" href="{{ seo.canonical }}">
{% for alt in seo.alternates %}<link rel="alternate" hreflang="{{ alt.language }}" href="{{ alt.url }}">{% endfor %}<link rel="alternate" hreflang="x-default" href="{{ seo.default_url }}">
<meta property="og:title" content="{{ seo.og_title }}"><meta property="og:description" content="{{ seo.og_description }}"><meta property="og:type" content="{{ seo.og_type }}"><meta property="og:url" content="{{ seo.canonical }}"><meta property="og:site_name" content="{{ seo.og_site_name }}">{% if seo.og_image %}<meta property="og:image" content="{{ seo.og_image }}">{% endif %}{% if seo.og_video %}<meta property="og:video" content="{{ seo.og_video }}">{% endif %}<meta property="og:locale" content="{% if current_language == 'ru' %}ru_RU{% elif current_language == 'kk' %}kk_KZ{% else %}en_US{% endif %}">
{% if site.google_verification %}<meta name="google-site-verification" content="{{ site.google_verification }}">{% endif %}{% if site.yandex_verification %}<meta name="yandex-verification" content="{{ site.yandex_verification }}">{% endif %}
<link rel="icon" href="{% static 'img/favicon.svg' %}" type="image/svg+xml"><link rel="preload" href="{% static 'fonts/golos-text.woff2' %}" as="font" type="font/woff2" crossorigin><link rel="preload" href="{% static 'fonts/exo2.woff2' %}" as="font" type="font/woff2" crossorigin>
{% block preload %}{% endblock %}{% asset_css 'frontend/main.js' as styles %}{% for href in styles %}<link rel="stylesheet" href="{{ href }}">{% endfor %}
{% for schema in schemas %}<script type="application/ld+json" nonce="{{ request.csp_nonce }}">{{ schema|json_ld }}</script>{% endfor %}
<script type="module" src="{% asset 'frontend/main.js' %}" defer></script></head>
<body class="{% block body_class %}{% endblock %}"><a class="skip-link" href="#main">{% trans 'Перейти к содержимому' %}</a>
<header class="site-header"><div class="header-inner"><a class="brand" href="{{ '/'|local_url }}" aria-label="Legion Auto Rent — {% trans 'Главная' %}"><img src="{% static 'img/logo.svg' %}" width="164" height="42" alt="Legion Auto Rent"></a>
<details class="city-menu"><summary><span class="location-dot" aria-hidden="true"></span>{% if city %}{{ city|tr:'name' }}{% else %}{% trans 'Выберите город' %}{% endif %}<span aria-hidden="true">⌄</span></summary><ul>{% for nav_city in nav_cities %}<li><a href="{{ nav_city.legacy_path|local_url }}">{{ nav_city|tr:'name' }}</a></li>{% endfor %}</ul></details>
<nav class="desktop-nav" aria-label="{% trans 'Главное меню' %}"><a href="{{ '/cars/'|local_url }}">{% trans 'Автопарк' %}</a><a href="{{ '/rental-conditions/'|local_url }}">{% trans 'Условия' %}</a><a href="{{ '/contacts/'|local_url }}">{% trans 'Контакты' %}</a></nav>
<div class="language-switch" aria-label="{% trans 'Язык' %}">{% for item in language_links %}<a href="{{ item.url }}" lang="{{ item.language }}" {% if item.language == current_language %}aria-current="true"{% endif %}>{{ item.label }}</a>{% endfor %}</div>
<a class="header-phone" href="tel:{{ site.phone|phone_link }}" data-event="click_phone">{{ site.phone }}</a>
<details class="mobile-menu"><summary aria-label="{% trans 'Открыть меню' %}"><span></span><span></span></summary><nav aria-label="{% trans 'Мобильное меню' %}"><a href="{{ '/cars/'|local_url }}">{% trans 'Автопарк' %}</a><a href="{{ '/rental-conditions/'|local_url }}">{% trans 'Условия аренды' %}</a><a href="{{ '/faq/'|local_url }}">FAQ</a><a href="{{ '/contacts/'|local_url }}">{% trans 'Контакты' %}</a><a href="tel:{{ site.phone|phone_link }}">{{ site.phone }}</a></nav></details></div></header>
<main id="main">{% if seo.fallback %}<div class="translation-notice container" role="note">{% trans 'Перевод этой страницы готовится. Пока показан русский текст.' %}</div>{% endif %}{% block content %}{% endblock %}</main>
<footer class="site-footer"><div class="container footer-top"><div><a class="brand" href="{{ '/'|local_url }}"><img src="{% static 'img/logo.svg' %}" width="164" height="42" alt="Legion Auto Rent"></a><p>{{ site|tr:'footer_text' }}</p><a class="footer-phone" href="tel:{{ site.phone|phone_link }}" data-event="click_phone">{{ site.phone }}</a></div><nav aria-label="{% trans 'Города' %}"><p class="eyebrow">{% trans 'Города' %}</p>{% for nav_city in nav_cities %}<a href="{{ nav_city.legacy_path|local_url }}">{{ nav_city|tr:'name' }}</a>{% endfor %}</nav><nav aria-label="{% trans 'Информация' %}"><p class="eyebrow">{% trans 'Информация' %}</p>{% for page in footer_pages %}<a href="{{ page.path|local_url }}">{{ page|tr:'title' }}</a>{% endfor %}<a href="{{ '/faq/'|local_url }}">FAQ</a></nav><div><p class="eyebrow">{% trans 'Мы на связи' %}</p><a href="{{ site.whatsapp_url }}" data-event="click_whatsapp">WhatsApp ↗</a>{% if site.instagram %}<a href="{{ site.instagram }}" rel="noopener noreferrer" target="_blank">Instagram ↗</a>{% endif %}<p>{{ site.address }}</p></div></div><div class="container footer-bottom"><span>© {% now 'Y' %} Legion Auto Rent</span><a href="{{ '/privacy/'|local_url }}">{% trans 'Конфиденциальность' %}</a><span>{% trans 'Без такси и доставки' %}</span></div></footer>
<div class="mobile-contact"><a href="tel:{{ site.phone|phone_link }}" data-event="click_phone">{% trans 'Позвонить' %} ↗</a><a class="mobile-wa" href="{{ site.whatsapp_url }}" data-mobile-wa data-event="click_whatsapp">WhatsApp ↗</a></div>
{% if analytics_enabled %}{% include 'components/analytics.html' %}{% endif %}
</body></html>''',
'templates/home.html':r'''{% extends 'base.html' %}{% load static i18n legion_tags %}{% block body_class %}home-page{% endblock %}
{% block preload %}<link rel="preload" as="image" href="{{ site.hero_poster_path }}" fetchpriority="high">{% endblock %}
{% block content %}<section class="hero" data-hero data-model="{% if site.hero_model %}{{ site.hero_model.url }}{% else %}{{ site.hero_model_path }}{% endif %}" data-enabled="{{ site.enable_hero_3d|yesno:'true,false' }}" data-video="{% if site.enable_hero_video %}{{ site.hero_video_path }}{% endif %}">
<img class="hero-poster" src="{{ site.hero_poster_path }}" width="1600" height="900" alt="{% trans 'Автомобиль в студийном освещении' %}" fetchpriority="high" decoding="async"><div class="hero-canvas" aria-hidden="true"></div><div class="hero-shade"></div>
<div class="container hero-content"><div class="hero-copy"><p class="eyebrow">LEGION AUTO RENT <span> / {{ city|tr:'name' }}</span></p><h1>{{ seo.h1 }}</h1><p class="hero-note">{{ city|tr:'hero_text' }}</p><a class="button" href="#fleet">{% trans 'Выбрать автомобиль' %}<span aria-hidden="true">↗</span></a><div class="hero-facts"><span><strong>{{ car_count }}</strong>{% trans 'автомобилей' %}</span><span><strong>04</strong>{% trans 'города' %}</span><span><strong>10 {% trans 'мин' %}</strong>{% trans 'оформление' %}</span></div></div>
<div class="hero-end"><p class="eyebrow">{% trans 'Всё начинается с вашего маршрута' %}</p><h2>{% trans 'Город ждёт.' %}<br>{% trans 'Вы за рулём.' %}</h2><p>{{ site|tr:'hero_text' }}</p><a class="text-link" href="#fleet">{% trans 'К автопарку' %} ↓</a></div></div>
<div class="hero-bottom container"><span>{% trans 'Без водителя. Под ваши планы.' %}</span><button type="button" class="light-toggle" data-light-toggle aria-pressed="false" hidden>{% trans 'Включить фары' %}</button><span class="hero-hint" hidden>{% trans 'Потяните, чтобы повернуть' %} ↔</span></div>
<script type="application/json" id="hero-names" nonce="{{ request.csp_nonce }}">{{ site.hero_names|json_ld }}</script></section>
{% include 'components/city_sections.html' %}{% endblock %}''',
'templates/city.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block content %}{% include 'components/breadcrumbs.html' %}<section class="city-hero container"><p class="eyebrow">LEGION AUTO RENT / {{ city|tr:'name' }}</p><h1>{{ seo.h1 }}</h1><p class="city-note">{{ city|tr:'hero_text' }}</p><a class="button" href="#fleet">{% trans 'Выбрать автомобиль' %} ↗</a><span class="city-car-count">{{ car_count }} {% trans 'автомобилей' %}</span></section>{% include 'components/city_sections.html' %}{% endblock %}''',
'templates/components/city_sections.html':r'''{% load i18n legion_tags %}<section class="section fleet-section" id="fleet"><div class="container"><div class="section-heading"><div><p class="eyebrow">01 / {% trans 'Ваш выбор' %}</p><h2>{% trans 'Автопарк' %}<span class="count">{{ car_count }}</span></h2></div><a class="text-link" href="{{ '/cars/'|local_url }}?city={{ city.slug }}">{% trans 'Все фильтры' %} ↗</a></div>
<form class="quick-filter" action="{{ '/cars/'|local_url }}" method="get"><input type="hidden" name="city" value="{{ city.slug }}"><div><label for="quick-category">{% trans 'Класс автомобиля' %}</label><select id="quick-category" name="category"><option value="">{% trans 'Все классы' %}</option>{% for cat in nav_categories %}<option value="{{ cat.slug }}">{{ cat|tr:'name' }}</option>{% endfor %}</select></div><div><label for="quick-from">{% trans 'Дата получения' %}</label><input id="quick-from" type="date" name="start_date"></div><div><label for="quick-to">{% trans 'Дата возврата' %}</label><input id="quick-to" type="date" name="end_date"></div><button class="button" type="submit">{% trans 'Найти автомобиль' %} ↗</button></form>
<p class="subtle filter-note">{% trans 'Наличие на выбранные даты подтвердит менеджер.' %}</p><div class="car-grid">{% for car in cars %}{% include 'components/car_card.html' %}{% empty %}<p>{% trans 'Автомобили уточняются. Позвоните нам.' %}</p>{% endfor %}</div></div></section>
{% if steps %}<section class="section steps-section"><div class="container"><p class="eyebrow">02 / {% trans 'Всё просто' %}</p><h2>{% trans '3 простых шага для аренды' %}</h2><div class="steps-grid">{% for step in steps %}<article><span class="step-number">0{{ forloop.counter }}</span><h3>{{ step|tr:'title' }}</h3><p>{{ step|tr:'text' }}</p></article>{% endfor %}</div></div></section>{% endif %}
{% if benefits %}<section class="section benefits-section"><div class="container"><div class="section-heading"><p class="eyebrow">03 / LEGION</p><h2>{% trans 'Ваши планы — в движении' %}</h2></div><div class="benefits-grid">{% for benefit in benefits %}<article><span aria-hidden="true">↗</span><h3>{{ benefit|tr:'title' }}</h3><p>{{ benefit|tr:'text' }}</p></article>{% endfor %}</div></div></section>{% endif %}
{% if city.body %}<section class="section seo-section"><div class="container prose">{{ city|tr:'body'|richtext }}</div></section>{% endif %}{% include 'components/faq.html' %}{% include 'components/partner.html' %}{% include 'components/contacts.html' %}''',
'templates/components/car_card.html':r'''{% load i18n legion_tags %}<article class="car-card"><a class="car-photo" href="{{ car.legacy_path|local_url }}" tabindex="-1" aria-hidden="true">{% with photo=car.main_image %}{% if photo %}<picture>{% if photo.card_avif_srcset %}<source type="image/avif" srcset="{{ photo.card_avif_srcset }}" sizes="(min-width:1280px) 390px,(min-width:768px) 46vw,92vw">{% endif %}<img src="{{ photo.card_url }}" {% if photo.card_srcset %}srcset="{{ photo.card_srcset }}" sizes="(min-width:1280px) 390px,(min-width:768px) 46vw,92vw"{% endif %} width="{{ photo.card_display_width }}" height="{{ photo.card_display_height }}" alt="{% firstof photo|tr:'alt' car.name %}" loading="lazy" decoding="async"></picture>{% else %}<span class="photo-empty">{{ car.brand.name }}</span>{% endif %}{% endwith %}<span class="car-category">{{ car.category|tr:'name' }}</span><span class="photo-arrow" aria-hidden="true">↗</span></a><div class="car-info"><h3><a href="{{ car.legacy_path|local_url }}">{{ car|tr:'name' }}</a></h3><p class="car-spec-line">{% if car.year %}{{ car.year }}{% endif %}{% if car.transmission %} · {{ car.get_transmission_display }}{% endif %}{% if car.engine %} · {{ car.engine }}{% endif %}{% if not car.year and not car.transmission and not car.engine %}{{ car.brand.name }} · {% trans 'Без водителя' %}{% endif %}</p><div class="car-price-row"><p><strong>{{ car.base_price|money }} ₸</strong><span> / {% trans 'сутки' %}</span></p><a class="car-detail-link" href="{{ car.legacy_path|local_url }}">{% trans 'Подробнее' %}<span aria-hidden="true"> ↗</span></a></div></div></article>''',
'templates/components/breadcrumbs.html':r'''{% load i18n %}{% if breadcrumbs %}<nav class="breadcrumbs container" aria-label="{% trans 'Навигационная цепочка' %}">{% for label,url in breadcrumbs %}{% if forloop.last %}<span aria-current="page">{{ label }}</span>{% else %}<a href="{{ url }}">{{ label }}</a><span aria-hidden="true">/</span>{% endif %}{% endfor %}</nav>{% endif %}''',
'templates/catalog.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block content %}{% include 'components/breadcrumbs.html' %}<section class="container catalog-heading"><p class="eyebrow">LEGION / {% trans 'Автопарк' %}</p><h1>{{ seo.h1 }}</h1><p>{% trans 'От городских поездок до особенных событий — выберите свой класс.' %}</p></section><section class="container catalog-layout"><aside class="catalog-sidebar"><form method="get" data-catalog-filter action="{{ request.path }}"><div class="filter-title"><h2>{% trans 'Фильтры' %}</h2><a class="text-link" href="{{ request.path }}">{% trans 'Сбросить' %}</a></div>{{ filter_form.non_field_errors }}{% for field in filter_form %}<div class="field{% if field.name == 'available' %} checkbox-field{% endif %}"><label for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}{{ field.errors }}</div>{% endfor %}<button class="button" type="submit">{% trans 'Показать автомобили' %} ↗</button><p class="subtle">{% trans 'Наличие на выбранные даты подтвердит менеджер.' %}</p></form></aside><div id="catalog-results" aria-live="polite">{% include 'components/catalog_results.html' %}</div></section>{% endblock %}''',
'templates/components/catalog_results.html':r'''{% load i18n legion_tags %}<div class="result-heading"><p>{{ cars.paginator.count }} {% trans 'автомобилей' %}</p><span class="subtle">{% trans 'Цена за сутки' %}</span></div>{% if filter_form.errors %}<p class="errorlist">{% trans 'Проверьте параметры поиска.' %}</p>{% endif %}<div class="car-grid catalog-grid">{% for car in cars %}{% include 'components/car_card.html' %}{% empty %}<div class="empty-state"><h2>{% trans 'Пока нет совпадений' %}</h2><p>{% trans 'Попробуйте изменить фильтры или свяжитесь с нами.' %}</p><a class="button" href="{{ site.whatsapp_url }}">WhatsApp ↗</a></div>{% endfor %}</div>{% if cars.paginator.num_pages > 1 %}<nav class="pagination" aria-label="{% trans 'Страницы каталога' %}">{% if cars.has_previous %}<a data-catalog-page href="?{{ pagination_query }}{% if pagination_query %}&amp;{% endif %}page={{ cars.previous_page_number }}">← {% trans 'Назад' %}</a>{% endif %}<span>{{ cars.number }} / {{ cars.paginator.num_pages }}</span>{% if cars.has_next %}<a data-catalog-page href="?{{ pagination_query }}{% if pagination_query %}&amp;{% endif %}page={{ cars.next_page_number }}">{% trans 'Далее' %} →</a>{% endif %}</nav>{% endif %}''',
'templates/car_detail.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block preload %}{% with photo=car.main_image %}{% if photo %}{% if photo.avif_srcset %}<link rel="preload" as="image" imagesrcset="{{ photo.avif_srcset }}" imagesizes="(min-width:1000px) 62vw,100vw" type="image/avif" fetchpriority="high">{% else %}<link rel="preload" as="image" href="{{ photo.display_url }}" fetchpriority="high">{% endif %}{% endif %}{% endwith %}{% endblock %}
{% block content %}{% include 'components/breadcrumbs.html' %}<section class="container car-heading"><p class="eyebrow">{{ car.category|tr:'name' }} / {{ car.brand.name }}</p><h1>{{ seo.h1 }}</h1><p class="subtle">{% for item in car.cities.all %}{{ item|tr:'name' }}{% if not forloop.last %} · {% endif %}{% endfor %}</p></section>
<div class="container car-detail-layout"><div class="car-story"><section class="gallery" data-gallery aria-label="{% trans 'Фотографии автомобиля' %}"><div class="gallery-track" tabindex="0">{% for photo in car.images.all %}<figure><picture>{% if photo.avif_srcset %}<source type="image/avif" srcset="{{ photo.avif_srcset }}" sizes="(min-width:1000px) 62vw,100vw">{% endif %}<img src="{{ photo.display_url }}" {% if photo.srcset %}srcset="{{ photo.srcset }}" sizes="(min-width:1000px) 62vw,100vw"{% endif %} width="{{ photo.width }}" height="{{ photo.height }}" alt="{% firstof photo|tr:'alt' car.name %}" {% if forloop.first %}fetchpriority="high"{% else %}loading="lazy"{% endif %} decoding="async"></picture>{% if photo.caption %}<figcaption>{{ photo.caption }}</figcaption>{% endif %}</figure>{% empty %}<div class="photo-empty">{{ car.name }}</div>{% endfor %}</div>{% if car.images.count > 1 %}<div class="gallery-controls"><button type="button" data-gallery-prev aria-label="{% trans 'Предыдущее фото' %}">←</button><span data-gallery-count>1 / {{ car.images.count }}</span><button type="button" data-gallery-next aria-label="{% trans 'Следующее фото' %}">→</button></div>{% endif %}</section>
<section class="detail-section"><p class="eyebrow">01 / {% trans 'Детали' %}</p><h2>{% trans 'Характеристики' %}</h2><dl class="specs">{% if car.year %}<div><dt>{% trans 'Год' %}</dt><dd>{{ car.year }}</dd></div>{% endif %}{% if car.engine %}<div><dt>{% trans 'Двигатель' %}</dt><dd>{{ car.engine }}</dd></div>{% endif %}{% if car.transmission %}<div><dt>{% trans 'Коробка' %}</dt><dd>{{ car.get_transmission_display }}</dd></div>{% endif %}{% if car.drive %}<div><dt>{% trans 'Привод' %}</dt><dd>{{ car.get_drive_display }}</dd></div>{% endif %}{% if car.fuel %}<div><dt>{% trans 'Топливо' %}</dt><dd>{{ car.fuel }}</dd></div>{% endif %}{% if car.seats %}<div><dt>{% trans 'Мест' %}</dt><dd>{{ car.seats }}</dd></div>{% endif %}{% if car.color %}<div><dt>{% trans 'Цвет' %}</dt><dd>{{ car.color }}</dd></div>{% endif %}{% if car.doors %}<div><dt>{% trans 'Дверей' %}</dt><dd>{{ car.doors }}</dd></div>{% endif %}{% for spec in car.extra_specs.all %}<div><dt>{{ spec|tr:'name' }}</dt><dd>{{ spec|tr:'value' }}</dd></div>{% endfor %}</dl>{% if not car.year and not car.engine and not car.transmission and not car.extra_specs.all %}<p class="subtle">{% trans 'Подробные характеристики уточните у менеджера.' %}</p>{% endif %}{% if car.description %}<div class="prose">{{ car|tr:'description'|richtext }}</div>{% endif %}</section>
<section class="detail-section"><p class="eyebrow">02 / {% trans 'Стоимость' %}</p><h2>{% trans 'Тарифы и скидки' %}</h2><div class="table-scroll"><table class="tariff-table"><caption class="sr-only">{% trans 'Стоимость аренды автомобиля' %}</caption><thead><tr><th scope="col">{% trans 'Срок аренды' %}</th><th scope="col">{% trans 'В сутки' %}</th><th scope="col">{% trans 'Депозит' %}</th><th scope="col">{% trans 'Пробег' %}</th></tr></thead><tbody>{% for price in car.prices.all %}<tr><th scope="row">{% if price.label %}{{ price.label }}{% else %}{{ price.min_days }}{% if price.max_days %}–{{ price.max_days }}{% else %}+{% endif %} {% trans 'дней' %}{% endif %}</th><td>{{ price.daily_price|money }} ₸</td><td>{% if price.deposit != None %}{{ price.deposit|money }} ₸{% else %}—{% endif %}</td><td>{% if price.mileage_limit %}{{ price.mileage_limit }} {% trans 'км/сутки' %}{% else %}—{% endif %}</td></tr>{% empty %}<tr><th scope="row">{% trans 'Базовый тариф' %}</th><td>{{ car.base_price|money }} ₸</td><td>{% if car.deposit != None %}{{ car.deposit|money }} ₸{% else %}—{% endif %}</td><td>{% if car.mileage_limit %}{{ car.mileage_limit }} {% trans 'км/сутки' %}{% else %}—{% endif %}</td></tr>{% endfor %}</tbody></table></div>{% if car.discounts.all %}<ul class="discounts">{% for discount in car.discounts.all %}<li><span>{{ discount.min_days }}{% if discount.max_days %}–{{ discount.max_days }}{% else %}+{% endif %} {% trans 'дней' %}</span><strong>−{{ discount.percent }}%</strong></li>{% endfor %}</ul>{% endif %}<p class="subtle">{% trans 'Итоговую стоимость, депозит и условия подтвердит менеджер.' %}</p></section>
<section class="detail-section"><p class="eyebrow">03 / {% trans 'Условия' %}</p><h2>{% trans 'До начала поездки' %}</h2><p>{% trans 'Для аренды нужны водительское удостоверение и удостоверение личности.' %}</p><p class="restriction">{% trans 'Под режим такси и доставки авто не сдаем!' %}</p>{% for block in conditions %}<details class="condition"><summary>{{ block|tr:'title' }}</summary><p>{{ block|tr:'text' }}</p></details>{% endfor %}<a class="text-link" href="{{ '/rental-conditions/'|local_url }}">{% trans 'Все условия аренды' %} ↗</a></section></div>
<aside class="booking-panel" data-car-booking data-car-name="{{ car|tr:'name' }}" data-city="{% if city %}{{ city|tr:'name' }}{% endif %}" data-whatsapp="{{ site.whatsapp }}" data-message="{{ car_whatsapp_message }}"><p class="eyebrow">{% trans 'Ваш автомобиль' %}</p><p class="booking-price">{{ car.base_price|money }} <span>₸ / {% trans 'сутки' %}</span></p><p class="subtle">{% trans 'Наличие на выбранные даты подтвердит менеджер.' %}</p>{% with form=booking_form compact=True %}{% include 'components/request_form.html' %}{% endwith %}<div class="booking-direct"><a class="button button-dark" href="tel:{{ site.phone|phone_link }}" data-event="click_phone">{% trans 'Позвонить' %} ↗</a>{% wa_url site.whatsapp car_whatsapp_message as car_wa %}<a class="button button-outline" href="{{ car_wa }}" data-car-wa data-event="click_whatsapp">WhatsApp ↗</a></div></aside></div>
{% include 'components/faq.html' %}{% if related_cars %}<section class="section"><div class="container"><div class="section-heading"><h2>{% trans 'Ещё в вашем классе' %}</h2><a class="text-link" href="{{ car.category.get_absolute_url|local_url }}">{% trans 'Все автомобили' %} ↗</a></div><div class="car-grid">{% for car in related_cars %}{% include 'components/car_card.html' %}{% endfor %}</div></div></section>{% endif %}{% endblock %}''',
'templates/components/request_form.html':r'''{% load i18n legion_tags %}<form method="post" action="{% if callback %}{{ '/callback/'|local_url }}{% else %}{{ '/booking/'|local_url }}{% endif %}" class="request-form" data-request-form>{% csrf_token %}{{ form.source_token }}<div class="honeypot" aria-hidden="true">{{ form.website.label_tag }}{{ form.website }}</div>{{ form.non_field_errors }}{% for field in form %}{% if field.name != 'source_token' and field.name != 'website' and field.name != 'consent' %}{% if compact and field.name == 'car' or compact and field.name == 'city' %}{{ field.as_hidden }}{% elif compact and field.name == 'comment' %}{% else %}<div class="field"><label for="{{ field.id_for_label }}">{{ field.label }}{% if field.field.required %}<span aria-hidden="true"> *</span>{% endif %}</label>{{ field }}{{ field.errors }}</div>{% endif %}{% endif %}{% endfor %}<div class="consent-field">{{ form.consent }}<label for="{{ form.consent.id_for_label }}">{{ form.consent.label }} <a href="{{ '/consent/'|local_url }}">{% trans 'Подробнее' %}</a></label>{{ form.consent.errors }}</div><button type="submit" class="button">{% if callback %}{% trans 'Заказать звонок' %}{% else %}{% trans 'Оставить заявку' %}{% endif %} ↗</button></form>''',
'templates/booking.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block content %}<section class="container form-page"><div><p class="eyebrow">LEGION / {% trans 'Мы на связи' %}</p><h1>{{ seo.h1 }}</h1><p>{% trans 'Менеджер уточнит детали и подтвердит условия аренды.' %}</p><a class="footer-phone" href="tel:{{ site.phone|phone_link }}">{{ site.phone }}</a></div><div class="form-surface">{% include 'components/request_form.html' %}</div></section>{% endblock %}''',
'templates/page.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block content %}{% include 'components/breadcrumbs.html' %}<section class="container page-heading"><p class="eyebrow">LEGION AUTO RENT</p><h1>{{ seo.h1 }}</h1></section><section class="container page-content prose">{{ page|tr:'body'|richtext }}</section>{% if page.slug == 'contacts' %}{% include 'components/contacts.html' %}{% endif %}{% include 'components/faq.html' %}{% endblock %}''',
'templates/faq_page.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block content %}<section class="container page-heading"><p class="eyebrow">LEGION / FAQ</p><h1>{{ seo.h1 }}</h1></section>{% include 'components/faq.html' %}{% include 'components/contacts.html' %}{% endblock %}''',
'templates/components/faq.html':r'''{% load i18n legion_tags %}{% if faqs %}<section class="section faq-section" id="faq"><div class="container faq-layout"><div><p class="eyebrow">FAQ</p><h2>{% trans 'Хороший вопрос.' %}<br>{% trans 'Понятный ответ.' %}</h2><p>{% trans 'Остались вопросы? Мы на связи.' %}</p><a class="text-link" href="{{ site.whatsapp_url }}" data-event="click_whatsapp">{% trans 'Спросить в WhatsApp' %} ↗</a></div><div class="faq-list">{% for faq in faqs %}<details><summary>{{ faq|tr:'question' }}<span aria-hidden="true">+</span></summary><div class="prose">{{ faq|tr:'answer'|richtext }}</div></details>{% endfor %}</div></div></section>{% endif %}''',
'templates/components/partner.html':r'''{% load i18n legion_tags %}{% if site.show_partner_section and partner_translated %}<section class="partner-section"><div class="container partner-inner"><div><p class="eyebrow">LEGION / {% trans 'Партнёрам' %}</p><h2>{{ site|tr:'partner_title' }}</h2></div><div><p>{{ site|tr:'partner_description' }}</p><div class="partner-actions">{% firstof site.partner_phone site.phone as partner_phone %}{% firstof site.partner_whatsapp site.whatsapp as partner_whatsapp %}{% with message=site|tr:'partner_whatsapp_message' %}{% wa_url partner_whatsapp message as partner_link %}<a class="partner-phone" href="tel:{{ partner_phone|phone_link }}" data-event="click_phone">{{ partner_phone }}</a><a class="button button-dark" href="{{ partner_link }}" data-event="click_whatsapp" data-context="partner">{% trans 'Написать в WhatsApp' %} ↗</a>{% endwith %}</div></div></div></section>{% endif %}''',
'templates/components/contacts.html':r'''{% load i18n legion_tags %}<section class="section contacts-section" id="contacts"><div class="container contact-layout"><div><p class="eyebrow">{% trans 'Мы рядом' %}</p><h2>{% trans 'Встретимся в Легионе' %}</h2><a class="contact-phone" href="tel:{% if city.phone %}{{ city.phone|phone_link }}{% else %}{{ site.phone|phone_link }}{% endif %}" data-event="click_phone">{% firstof city.phone site.phone %}</a><p>{% if city %}{{ city|tr:'address' }}{% else %}{{ site.address }}{% endif %}</p>{% if city.hours %}<p>{{ city.hours }}</p>{% elif site.hours %}<p>{{ site.hours }}</p>{% endif %}<div class="contact-actions"><a class="text-link" href="{{ site.whatsapp_url }}" data-event="click_whatsapp">WhatsApp ↗</a><a class="text-link" href="{{ '/callback/'|local_url }}">{% trans 'Заказать звонок' %} ↗</a></div></div><div class="contact-map">{% firstof city.map_url site.map_url as map_url %}{% if map_url %}<details data-map><summary>{% trans 'Показать на карте' %}<span aria-hidden="true">↗</span></summary><iframe title="{% trans 'Карта проезда к Legion Auto Rent' %}" data-src="{{ map_url }}" width="640" height="360" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><noscript><a href="{{ map_url }}" rel="noopener noreferrer">{% trans 'Открыть карту' %}</a></noscript></details>{% endif %}<div class="map-address"><span aria-hidden="true">↗</span><p>{% firstof city.address site.address %}</p><a href="{{ '/contacts/'|local_url }}">{% trans 'Все контакты' %} ↗</a></div></div></div></section>''',
'templates/success.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block content %}<section class="container error-page" {% if submitted %}data-page-event="booking_submit"{% endif %}><p class="eyebrow">LEGION / {% trans 'Спасибо' %}</p><h1>{{ seo.h1 }}</h1><p>{% trans 'Менеджер свяжется с вами для уточнения деталей.' %}</p><a class="button" href="{{ '/cars/'|local_url }}">{% trans 'К автопарку' %} ↗</a></section>{% endblock %}''',
'templates/404.html':r'''{% extends 'base.html' %}{% load i18n legion_tags %}{% block content %}<section class="container error-page"><p class="error-code">404</p><h1>{{ seo.h1 }}</h1><p>{% trans 'Этот маршрут пока недоступен. Выберите автомобиль в каталоге.' %}</p><a class="button" href="{{ '/cars/'|local_url }}">{% trans 'К автопарку' %} ↗</a></section>{% endblock %}''',
'templates/500.html':r'''{% load i18n %}<!doctype html><html lang="{{ language }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{% trans 'Сервис временно недоступен' %}</title><style>body{margin:0;background:#1f1f1f;color:#fff;font:20px/1.5 system-ui}main{max-width:800px;margin:15vh auto;padding:24px}h1{font-size:40px}a{color:#f7b500}p:first-child{font-size:80px;margin:0}</style></head><body><main><p>500</p><h1>{% trans 'Сервис временно недоступен' %}</h1><p>{% trans 'Попробуйте позже или позвоните нам.' %}</p><a href="tel:+77057277777">+7 (705) 727-77-77</a></main></body></html>''',
'templates/components/analytics.html':r'''<div hidden data-analytics data-gtm="{{ site.gtm_id }}" data-ga="{{ site.ga4_id }}" data-metrika="{{ site.metrika_id }}"></div>''',
'static/img/favicon.svg':r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="#1f1f1f"/><path d="M17 13h10v37h24v7H17z" fill="#f7b500"/></svg>''',
}
for name,content in files.items():
    path=ROOT/name;path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content+'\n',encoding='utf8')
print(f'Wrote {len(files)} new templates/assets.')
