# Generated by Django 5.2.17 on 2026-10-02 09:53

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='H1')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical override')),
                ('robots', models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40)),
                ('og_title', models.CharField(blank=True, max_length=250)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('name_in', models.CharField(blank=True, max_length=120, verbose_name='Предложный падеж')),
                ('slug', models.SlugField(unique=True)),
                ('legacy_path', models.CharField(max_length=250, unique=True, validators=[seo.models.validate_local_path])),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, verbose_name='SEO-текст (HTML)')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('map_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
