# Generated by Django 5.2.17 on 2026-10-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_legacy_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hero_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='hours',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
