# Generated by Django 5.2.17 on 2026-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_hero_text_city_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные Open Graph/Twitter поля сохранены для точной миграции.'),
        ),
    ]
