# Generated by Django 5.2.17 on 2026-10-05 09:40

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_city_legacy_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='city',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='city',
            name='hero_text',
            field=models.TextField(blank=True, verbose_name='Описание первого экрана'),
        ),
        migrations.AlterField(
            model_name='city',
            name='hours',
            field=models.CharField(blank=True, max_length=120, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные Open Graph/Twitter поля сохранены для точной миграции.', verbose_name='Сохранённые метаданные'),
        ),
        migrations.AlterField(
            model_name='city',
            name='legacy_path',
            field=models.CharField(blank=True, help_text='Пустое поле: автоматически /slug/. Существующий путь не меняется.', max_length=250, unique=True, validators=[seo.models.validate_local_path], verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='map_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на встроенную карту Яндекса'),
        ),
        migrations.AlterField(
            model_name='city',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='city',
            name='og_image',
            field=models.URLField(blank=True, verbose_name='Адрес картинки для соцсетей'),
        ),
        migrations.AlterField(
            model_name='city',
            name='og_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='city',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='city',
            name='robots',
            field=models.CharField(choices=[('index,follow', 'Индексировать'), ('noindex,follow', 'Не индексировать')], default='index,follow', max_length=40, verbose_name='Индексация'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код в адресе (slug)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='city',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер WhatsApp'),
        ),
    ]
