# Generated by Django 5.2.17 on 2026-10-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('consent_text', models.TextField(blank=True)),
                ('manager_note', models.TextField(blank=True, verbose_name='Заметка менеджера')),
                ('source_page', models.CharField(blank=True, max_length=600)),
                ('landing_page', models.CharField(blank=True, max_length=600)),
                ('referrer', models.CharField(blank=True, max_length=600)),
                ('utm_source', models.CharField(blank=True, max_length=200)),
                ('utm_medium', models.CharField(blank=True, max_length=200)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('CONTACTED', 'Связались'), ('CONFIRMED', 'Подтверждена'), ('CANCELLED', 'Отменена'), ('COMPLETED', 'Завершена')], db_index=True, default='NEW', max_length=20)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.car')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city')),
            ],
            options={
                'verbose_name': 'Заявка на аренду',
                'verbose_name_plural': 'Заявки на аренду',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('start_date__isnull', True)), models.Q(('end_date__gt', models.F('start_date')), ('end_date__isnull', False), ('start_date__isnull', False)), _connector='OR'), name='valid_booking_dates')],
            },
        ),
    ]
