# Generated by Django 5.2.17 on 2026-10-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='kind',
            field=models.CharField(choices=[('booking', 'Аренда'), ('callback', 'Обратный звонок')], db_index=True, default='booking', max_length=20),
        ),
    ]
