# Generated by Django 5.2.17 on 2026-10-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingrequest_kind'),
        ('cars', '0006_alter_carbrand_options_alter_cardiscount_options_and_more'),
        ('locations', '0005_alter_city_active_alter_city_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Согласие клиента'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='consent_text',
            field=models.TextField(blank=True, verbose_name='Текст согласия'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец аренды'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='kind',
            field=models.CharField(choices=[('booking', 'Аренда'), ('callback', 'Обратный звонок')], db_index=True, default='booking', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='landing_page',
            field=models.CharField(blank=True, max_length=600, verbose_name='Страница входа'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='referrer',
            field=models.CharField(blank=True, max_length=600, verbose_name='Источник перехода'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='source_page',
            field=models.CharField(blank=True, max_length=600, verbose_name='Страница заявки'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало аренды'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('CONTACTED', 'Связались'), ('CONFIRMED', 'Подтверждена'), ('CANCELLED', 'Отменена'), ('COMPLETED', 'Завершена')], db_index=True, default='NEW', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ratelimitbucket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
