# Generated by Django 5.2.17 on 2026-10-02 09:53

import django.db.models.deletion
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=500, unique=True, validators=[seo.models.validate_local_path])),
                ('new_path', models.CharField(max_length=500, validators=[seo.models.validate_local_path])),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('language', models.CharField(choices=[('kk', 'KZ / Қазақша'), ('en', 'EN / English')], max_length=2, verbose_name='Язык')),
                ('published', models.BooleanField(default=False, verbose_name='Перевод проверен и опубликован')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title / заголовок блока')),
                ('description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('h1', models.CharField(blank=True, max_length=250, verbose_name='H1')),
                ('content', models.TextField(blank=True, verbose_name='Контент / ответ / HTML')),
                ('intro', models.TextField(blank=True, verbose_name='Вводный текст')),
                ('og_title', models.CharField(blank=True, max_length=250)),
                ('og_description', models.TextField(blank=True)),
                ('hero_title', models.CharField(blank=True, max_length=250, verbose_name='Hero заголовок')),
                ('hero_text', models.TextField(blank=True)),
                ('partner_title', models.CharField(blank=True, max_length=250)),
                ('partner_description', models.TextField(blank=True)),
                ('partner_whatsapp_message', models.TextField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы KZ / EN',
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'language'), name='unique_object_translation')],
            },
        ),
    ]
