# Generated by Django 5.2.17 on 2026-10-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='translation',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='translation',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='translation',
            name='fuel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='translation',
            name='hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='translation',
            name='whatsapp_message',
            field=models.TextField(blank=True),
        ),
    ]
