# Generated by Django 5.2.17 on 2026-10-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_translation_address_translation_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='hero_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Финальная подпись Hero (не H1)'),
        ),
    ]
