# Generated by Django 5.2.17 on 2026-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_translation_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='hero_price_caption',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подпись Hero о цене'),
        ),
        migrations.AddField(
            model_name='translation',
            name='hero_steps_caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='Три шага Hero'),
        ),
    ]
