# Generated by Django 5.2.17 on 2026-10-05 09:40

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_translation_hero_price_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'verbose_name': 'Перенаправление', 'verbose_name_plural': 'Перенаправления'},
        ),
        migrations.AlterField(
            model_name='redirect',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(max_length=500, validators=[seo.models.validate_local_path], verbose_name='Конечный адрес'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(max_length=500, unique=True, validators=[seo.models.validate_local_path], verbose_name='Старый адрес'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301, verbose_name='Код ответа'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='footer_text',
            field=models.CharField(blank=True, max_length=250, verbose_name='Подпись в подвале'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='fuel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='hero_text',
            field=models.TextField(blank=True, verbose_name='Описание первого экрана'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='hours',
            field=models.CharField(blank=True, max_length=120, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='og_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='partner_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='partner_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='partner_whatsapp_message',
            field=models.TextField(blank=True, verbose_name='Сообщение для партнёров'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='whatsapp_message',
            field=models.TextField(blank=True, verbose_name='Сообщение в WhatsApp'),
        ),
    ]
